### PR TITLE
Liferay 7.0 support

### PR DESCRIPTION
**Pull request by slemarchand**
Hi @juangon,

Here is a first beta version for XMLPF 4.0, including basic support for Liferay 7.0 (a requested in #5).

Only basic features are covered by the 4.0-beta1 version.

Cheers

[XMLPortletFactory_4.0-beta1.zip](https://github.com/xmlportletfactory/xmlportletfactory/files/953850/XMLPortletFactory_4.0-beta1.zip)

### CODE REVIEW

**Comment by juangon** [comment]
Hi @slemarchand. I am waiting for Liferay GA4 to be released, as there would be probably some API changes and improvements. Then I will try to find some time to review your great pull request, and probably add some missing stuff if any.

**Comment by slemarchand** [comment]
Hi @juangon,

Thanks for your answer.

> I am waiting for Liferay GA4 to be released, as there would be probably some API changes and improvements. 

I don't think there will be any revelant change for XMLPF in Liferay 7 GA4, and unfortunately there is no release date planned for GA4 (so, it would be possible that we wait for months and months).

My feeling is that it's better for XMLPF to have a release planning independent from the release planning of Liferay Portal product.

> Then I will try to find some time to review your great pull request, and probably add some missing stuff if any.

Because it's a "4.0 beta 1" version, maybe there is no need for "deep-testing" at this stage. 

Futhermore, there is intentionally a lot of "missing stuff". As mentionned in my previous comment, only basic features are covered by the 4.0-beta1 version (to be more precise, only the features required by SchoolCoursesExample.xml sample file are covered). I have planned to cover the missing stuff later (versions "4.0 beta 2", "4.0 beta 3", etc).

To be totally transparent, my initial intention was to begin with just a small contribution as pull request to try to reactivate the XMLPF project (inactive for 3 years), and keep contributing gradually, little by little, with write permission on the repository.

**Comment by juangon** [comment]
> I don't think there will be any revelant change for XMLPF in Liferay 7 GA4, and unfortunately there is no release date planned for GA4 (so, it would be possible that we wait for months and months).

Don't worry about that. It should be released pretty sound. They had some problems in previous candidates but AFAIK it should be released very soon (days/few weeks).

> I don't think there will be any revelant change for XMLPF in Liferay 7 GA4, and unfortunately there is no release date planned for GA4 (so, it would be possible that we wait for months and months).

Let's see, sometimes there are improvements, changes in API that we could get some advantage from.

> My feeling is that it's better for XMLPF to have a release planning independent from the release planning of Liferay Portal product.

Sure! I just wanted to wait to this release for the number of improvements/changes it will have.

> Because it's a "4.0 beta 1" version, maybe there is no need for "deep-testing" at this stage.

> Futhermore, there is intentionally a lot of "missing stuff". As mentionned in my previous comment, only basic features are covered by the 4.0-beta1 version (to be more precise, only the features required by SchoolCoursesExample.xml sample file are covered). I have planned to cover the missing stuff later (versions "4.0 beta 2", "4.0 beta 3", etc).

> To be totally transparent, my initial intention was to begin with just a small contribution as pull request to try to reactivate the XMLPF project (inactive for 3 years), and keep contributing gradually, little by little, with write permission on the repository.

I see your point, but that's not how previous versions worked before. We prefer have something "minimal" working and tested. Take into account we have to support some XML so every possibility should be covered even for new versions.

**Comment by slemarchand** [comment]
Hi @juangon,

Thanks for your quick reply.

I learned today, by [this blog post](https://web.liferay.com/fr/web/yasuyuki.takeo/blog/-/blogs/damascus-a-scaffolding-service-builder-portlet-with-crud-search-workflow-and-more-functionalities-for-liferay-dxp-7-0), the existence of the [Damascus](https://github.com/yasuflatland-lf/damascus) project, a new CRUD generator for Liferay 7.0 / DXP, made by @yasuflatland-lf.

[Damascus](https://github.com/yasuflatland-lf/damascus) covers most of XMLPF features (it seems to be a full rewrite of XMLPF, but keeping the same spririt) and is based on recent technologies (Java 8, Gradle and Freemarker). So, now my feeling is that contributing to Damascus is more valuable for the community than finalizing the Liferay 7.0 / DXP support for XMLPF.

In the end, you were undoubtedly right to wait ;-)

**Pull request closed without merging**
